name: Publish to Pypi

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: robinraju/release-downloader@v1
      with:
        repository: "rndazurescript/Coco2CustomVision"
        latest: true
    - name: List artifacts
      run: |
        ls -la
